// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8zSKFEp5TzuG2ypMveiNcx2RfwhNLZtI',
    appId: '1:763725513957:web:d0b0c82fab35807300c00c',
    messagingSenderId: '763725513957',
    projectId: 'dcb-5323-water-safety-capstone',
    authDomain: 'dcb-5323-water-safety-capstone.firebaseapp.com',
    storageBucket: 'dcb-5323-water-safety-capstone.firebasestorage.app',
    measurementId: 'G-GD9DCFM4W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYivkP6TsDGMfQEgFP91nF0wY7eYGFMoY',
    appId: '1:763725513957:android:376879cba6fcf6d000c00c',
    messagingSenderId: '763725513957',
    projectId: 'dcb-5323-water-safety-capstone',
    storageBucket: 'dcb-5323-water-safety-capstone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMXSP54lFpBCcqB-Z_MXdswzYRe0cLRp0',
    appId: '1:763725513957:ios:81a4d881016905d500c00c',
    messagingSenderId: '763725513957',
    projectId: 'dcb-5323-water-safety-capstone',
    storageBucket: 'dcb-5323-water-safety-capstone.firebasestorage.app',
    iosClientId: '763725513957-i3sa3v7ldkj7dmonb05vq7m3cdh46ant.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterSafetyApp',
  );
}
